version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_server
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: todo_user
      DB_PASSWORD: todo_password
      DB_NAME: todo_db
      JWT_SECRET: your_secret_key
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres_data:
